/*
 * NOTICE:
 * This file auto generated by isp/common/code_gen/code_operator.py!
 * Please do not modify this file manually!
 */
//--------------------------------------------------------------------------------
// LSC <<<<<<<<
//--------------------------------------------------------------------------------
#define ISP_MLSC_COLOR_TEMPERATURE_SIZE (7)
#define CVI_ISP_LSC_GRID_POINTS (1369)

typedef struct _ISP_MESH_SHADING_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
} ISP_MESH_SHADING_ATTR_S;

typedef struct _ISP_MESH_SHADING_GAIN_LUT_S {
	CVI_U16 ColorTemperature; /*RW; Range: [0x0, 0x7530]*/
	CVI_U16 RGain[CVI_ISP_LSC_GRID_POINTS]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 GGain[CVI_ISP_LSC_GRID_POINTS]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 BGain[CVI_ISP_LSC_GRID_POINTS]; /*RW; Range: [0x0, 0xfff]*/
} ISP_MESH_SHADING_GAIN_LUT_S;

typedef struct _ISP_MESH_SHADING_GAIN_LUT_ATTR_S {
	CVI_U8 Size; /*RW; Range: [0x1, 0x7]*/
	ISP_MESH_SHADING_GAIN_LUT_S LscGainLut[ISP_MLSC_COLOR_TEMPERATURE_SIZE];
} ISP_MESH_SHADING_GAIN_LUT_ATTR_S;
//--------------------------------------------------------------------------------
// LSC >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// BLC <<<<<<<<
//--------------------------------------------------------------------------------
typedef struct _ISP_BLACK_LEVEL_MANUAL_ATTR_S {
	CVI_U16 OffsetR; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 OffsetGr; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 OffsetGb; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 OffsetB; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 OffsetR2; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 OffsetGr2; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 OffsetGb2; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 OffsetB2; /*RW; Range: [0x0, 0xfff]*/
} ISP_BLACK_LEVEL_MANUAL_ATTR_S;

typedef struct _ISP_BLACK_LEVEL_AUTO_ATTR_S {
	CVI_U16 OffsetR[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 OffsetGr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 OffsetGb[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 OffsetB[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 OffsetR2[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 OffsetGr2[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 OffsetGb2[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 OffsetB2[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
} ISP_BLACK_LEVEL_AUTO_ATTR_S;

typedef struct _ISP_BLACK_LEVEL_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
	ISP_BLACK_LEVEL_MANUAL_ATTR_S stManual;
	ISP_BLACK_LEVEL_AUTO_ATTR_S stAuto;
} ISP_BLACK_LEVEL_ATTR_S;
//--------------------------------------------------------------------------------
// BLC >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// FSHDR <<<<<<<<
//--------------------------------------------------------------------------------
#define FS_DIFF_DW_LENGTH (16)
#define FS_FLUMW_LUT_LENGTH (17)

typedef enum _ISP_MCURVE_MODE_E {
	MCURVE_AUTO,
	MCURVE_MANUAL_SEMAX,
} ISP_MCURVE_MODE_E;

typedef struct _ISP_FSHDR_ATTR_S {
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
	CVI_BOOL FusionEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 FusionMode; /*RW; Range: [0x0, 0x2]*/
	CVI_U8 FusionDbgMode; /*RW; Range: [0x0, 0x4]*/
	CVI_U8 FusionYsel; /*RW; Range: [0x0, 0x2]*/
	CVI_U8 FusionBldNsel; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 FusionBldDsel; /*RW; Range: [0x0, 0x1]*/
	CVI_U16 FusionDS1Th; /*RW; Range: [0x0, 0xfff]*/
	CVI_U8 FusionDS1Step; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 FusionDS1Lb; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 FusionDS2Th; /*RW; Range: [0x0, 0xfff]*/
	CVI_U8 FusionDS2Step; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 FusionDS2Lb; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 LENormBldRange; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 LENormBldP0; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 SENormBldRange; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 SENormBldP0; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 LEDynmBldRange; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 LEDynmBldP0; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 SEDynmBldRange; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 SEDynmBldP0; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 NDBldLumTh; /*RW; Range: [0x0, 0x100]*/
	CVI_U8 NDBldDarkWt; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 NDBldDiffLut[FS_DIFF_DW_LENGTH]; /*RW; Range: [0x0, 0x10]*/
	CVI_BOOL MCurveEnable; /*RW; Range: [0x0, 0x1]*/
	ISP_MCURVE_MODE_E MCurveMode; /*RW; Range: [0x0, 0x1]*/
	CVI_U16 MCurveAutoSEMin; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 MCurveManualSEMax; /*RW; Range: [0x0, 0xfff]*/
	CVI_U8 MCurveSmooth; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 MCurveDelta; /*RW; Range: [0x0, 0x2170]*/
	CVI_U16 MCurveX1; /*RW; Range: [0x0, 0xffff]*/
	CVI_U8 MCurveBldRatio; /*RW; Range: [0x0, 0xa]*/
	CVI_U16 MCurveXMaxRatio; /*RW; Range: [0x0, 0x100]*/
	CVI_U8 MCurveYsel; /*RW; Range: [0x0, 0x2]*/
	CVI_U8 MCurveYvWet; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 MCurveFlumWet[FS_FLUMW_LUT_LENGTH]; /*RW; Range: [0x0, 0xff]*/
} ISP_FSHDR_ATTR_S;
//--------------------------------------------------------------------------------
// FSHDR >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// DPC <<<<<<<<
//--------------------------------------------------------------------------------
#define DP_THR_LUT_NUM (5)

typedef struct _ISP_DP_DYNAMIC_MANUAL_ATTR_S {
	CVI_U8 DefectCnt1; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 DefectCnt2; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 AdvMode; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 AvgMode; /*RW; Range: [0x0, 0x1]*/
} ISP_DP_DYNAMIC_MANUAL_ATTR_S;

typedef struct _ISP_DP_DYNAMIC_AUTO_ATTR_S {
	CVI_U8 DefectCnt1[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 DefectCnt2[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 AdvMode[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 AvgMode[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x1]*/
} ISP_DP_DYNAMIC_AUTO_ATTR_S;

typedef struct _ISP_DP_DYNAMIC_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 DarkDefectThresh[DP_THR_LUT_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 BrightDefectThresh[DP_THR_LUT_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 DarkDefectThreshOffset; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 BrightDefectThreshOffset; /*RW; Range: [0x0, 0xfff]*/
	CVI_U8 TransitionWeight; /*RW; Range: [0x0, 0xff]*/
	ISP_DP_DYNAMIC_MANUAL_ATTR_S stManual;
	ISP_DP_DYNAMIC_AUTO_ATTR_S stAuto;
} ISP_DP_DYNAMIC_ATTR_S;
//--------------------------------------------------------------------------------
// DPC >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Crosstalk <<<<<<<<
//--------------------------------------------------------------------------------
typedef struct _ISP_CROSSTALK_MANUAL_ATTR_S {
	CVI_U16 Strength; /*RW; Range: [0x0, 0x100]*/
} ISP_CROSSTALK_MANUAL_ATTR_S;

typedef struct _ISP_CROSSTALK_AUTO_ATTR_S {
	CVI_U16 Strength[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x100]*/
} ISP_CROSSTALK_AUTO_ATTR_S;

typedef struct _ISP_CROSSTALK_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 GrGbDiffThreSec[4]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 FlatThre[4]; /*RW; Range: [0x0, 0xfff]*/
	ISP_CROSSTALK_MANUAL_ATTR_S stManual;
	ISP_CROSSTALK_AUTO_ATTR_S stAuto;
} ISP_CROSSTALK_ATTR_S;
//--------------------------------------------------------------------------------
// Crosstalk >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// BNR <<<<<<<<
//--------------------------------------------------------------------------------
#define BNR_WEIGHT_LUT_NUM (10)
#define BNR_BASE_LUT_NUM (6)
#define BNR_LUMA_LUT_NUM (17)

typedef struct _ISP_BNR_MANUAL_ATTR_S {
	CVI_U8 FilterKsize; /*RW; Range: [0x0, 0x1]*/
	CVI_U16 PreFilterStdThr1; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 PreFilterStdThr2; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U8 GussianKernelWt[BNR_WEIGHT_LUT_NUM]; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 NrBlendWt; /*RW; Range: [0x0, 0x10]*/
} ISP_BNR_MANUAL_ATTR_S;

typedef struct _ISP_BNR_AUTO_ATTR_S {
	CVI_U8 FilterKsize[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x1]*/
	CVI_U16 PreFilterStdThr1[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 PreFilterStdThr2[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U8 GussianKernelWt[BNR_WEIGHT_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 NrBlendWt[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x10]*/
} ISP_BNR_AUTO_ATTR_S;

typedef struct _ISP_BNR_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
	CVI_BOOL PreFilterEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL PreFilterModeSel; /*RW; Range: [0x0, 0x1]*/
	ISP_BNR_MANUAL_ATTR_S stManual;
	ISP_BNR_AUTO_ATTR_S stAuto;
} ISP_BNR_ATTR_S;

typedef struct _ISP_BNR_FILTER_MANUAL_ATTR_S {
	CVI_U16 Filter1GaussianCurve[BNR_BASE_LUT_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 Filter1LumaOffset[BNR_LUMA_LUT_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 Filter2GaussianCurve[BNR_BASE_LUT_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 Filter2LumaOffset[BNR_LUMA_LUT_NUM]; /*RW; Range: [0x0, 0x3ff]*/
} ISP_BNR_FILTER_MANUAL_ATTR_S;

typedef struct _ISP_BNR_FILTER_AUTO_ATTR_S {
	CVI_U16 Filter1GaussianCurve[BNR_BASE_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 Filter1LumaOffset[BNR_LUMA_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 Filter2GaussianCurve[BNR_BASE_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 Filter2LumaOffset[BNR_LUMA_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
} ISP_BNR_FILTER_AUTO_ATTR_S;

typedef struct _ISP_BNR_FILTER_ATTR_S {
	CVI_U8 DebugMode; /*RW; Range: [0x0, 0x3]*/
	ISP_BNR_FILTER_MANUAL_ATTR_S stManual;
	ISP_BNR_FILTER_AUTO_ATTR_S stAuto;
} ISP_BNR_FILTER_ATTR_S;
//--------------------------------------------------------------------------------
// BNR >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// RLSC <<<<<<<<
//--------------------------------------------------------------------------------
#define ISP_RLSC_WINDOW_SIZE (32)

typedef struct _ISP_RADIAL_SHADING_MANUAL_ATTR_S {
	CVI_U16 RadiusStr; /*RW; Range: [0x0, 0xfff]*/
	CVI_U8 NDStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 NDThr; /*RW; Range: [0x0, 0xff]*/
} ISP_RADIAL_SHADING_MANUAL_ATTR_S;

typedef struct _ISP_RADIAL_SHADING_AUTO_ATTR_S {
	CVI_U16 RadiusStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U8 NDStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 NDThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
} ISP_RADIAL_SHADING_AUTO_ATTR_S;

typedef struct _ISP_RADIAL_SHADING_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 CenterX; /*RW; Range: [0x0, 0x1fff]*/
	CVI_U16 CenterY; /*RW; Range: [0x0, 0x1fff]*/
	CVI_U16 RadiusScaleRGB; /*RW; Range: [0x0, 0x7fff]*/
	ISP_RADIAL_SHADING_MANUAL_ATTR_S stManual;
	ISP_RADIAL_SHADING_AUTO_ATTR_S stAuto;
} ISP_RADIAL_SHADING_ATTR_S;

typedef struct _ISP_RADIAL_SHADING_GAIN_LUT_ATTR_S {
	CVI_U16 GGain[ISP_RLSC_WINDOW_SIZE]; /*RW; Range: [0x0, 0xfff]*/
} ISP_RADIAL_SHADING_GAIN_LUT_ATTR_S;
//--------------------------------------------------------------------------------
// RLSC >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// DRC <<<<<<<<
//--------------------------------------------------------------------------------
typedef struct _ISP_DRC_MANUAL_ATTR_S {
	CVI_U8 Strength; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 StrengthMin; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 StrengthMax; /*RW; Range: [0x0, 0xff]*/
} ISP_DRC_MANUAL_ATTR_S;

typedef struct _ISP_DRC_AUTO_ATTR_S {
	CVI_U8 Strength[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 StrengthMin[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 StrengthMax[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
} ISP_DRC_AUTO_ATTR_S;

typedef struct _ISP_DRC_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
	CVI_BOOL AutoMode; /*RW; Range: [0x0, 0x1]*/
	CVI_U16 SaturationLow; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 SaturationHigh; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 ContrastLow; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 ContrastHigh; /*RW; Range: [0x0, 0xfff]*/
	CVI_U8 BlockNumW; /*RW; Range: [0x7, 0x2f]*/
	CVI_U8 GainUB; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 GainLB; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 GainProtStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 FSBPstr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 DeFlareMode; /*RW; Range: [0x0, 0x2]*/
	CVI_U8 DeFlareRatio; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 DeFlareSlope; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 AdaptiveLowStr; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 AdaptiveHighStr; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 AdaptiveRatio; /*RW; Range: [0x0, 0x3e8]*/
	CVI_U8 ColorProtStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 ColorProtThr; /*RW; Range: [0x0, 0xfff]*/
	ISP_DRC_MANUAL_ATTR_S stManual;
	ISP_DRC_AUTO_ATTR_S stAuto;
} ISP_DRC_ATTR_S;
//--------------------------------------------------------------------------------
// DRC >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// DEMOSAIC <<<<<<<<
//--------------------------------------------------------------------------------
typedef struct _ISP_DEMOSAIC_MANUAL_ATTR_S {
	CVI_U16 CoarseEdgeThr; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 CoarseStr; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 FineEdgeThr; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 FineStr; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 RbSigLumaThd; /*RW; Range: [0x0, 0xfff]*/
	CVI_U8 FilterMode; /*RW; Range: [0x0, 0x1]*/
} ISP_DEMOSAIC_MANUAL_ATTR_S;

typedef struct _ISP_DEMOSAIC_AUTO_ATTR_S {
	CVI_U16 CoarseEdgeThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 CoarseStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 FineEdgeThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 FineStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 RbSigLumaThd[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U8 FilterMode[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x1]*/
} ISP_DEMOSAIC_AUTO_ATTR_S;

typedef struct _ISP_DEMOSAIC_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
	CVI_BOOL TuningMode; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL RbVtEnable; /*RW; Range: [0x0, 0x1]*/
	ISP_DEMOSAIC_MANUAL_ATTR_S stManual;
	ISP_DEMOSAIC_AUTO_ATTR_S stAuto;
} ISP_DEMOSAIC_ATTR_S;

typedef struct _ISP_DEMOSAIC_DEMOIRE_MANUAL_ATTR_S {
	CVI_U8 AntiFalseColorStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 SatGainIn[2]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 SatGainOut[2]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 ProtectColorGainIn[2]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 ProtectColorGainOut[2]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 UserDefineProtectColor1; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 UserDefineProtectColor2; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 UserDefineProtectColor3; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 EdgeGainIn[2]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 EdgeGainOut[2]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 DetailGainIn[2]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 DetailGaintOut[2]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 DetailDetectLumaStr; /*RW; Range: [0x0, 0xfff]*/
	CVI_U8 DetailSmoothStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 DetailWgtThr; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 DetailWgtMin; /*RW; Range: [0x0, 0x100]*/
	CVI_U16 DetailWgtMax; /*RW; Range: [0x0, 0x100]*/
	CVI_U16 DetailWgtSlope; /*RW; Range: [0x0, 0x400]*/
	CVI_U8 EdgeWgtNp; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EdgeWgtThr; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 EdgeWgtMin; /*RW; Range: [0x0, 0x100]*/
	CVI_U16 EdgeWgtMax; /*RW; Range: [0x0, 0x100]*/
	CVI_U16 EdgeWgtSlope; /*RW; Range: [0x0, 0x400]*/
	CVI_U8 DetailSmoothMapTh; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 DetailSmoothMapMin; /*RW; Range: [0x0, 0x100]*/
	CVI_U16 DetailSmoothMapMax; /*RW; Range: [0x0, 0x100]*/
	CVI_U16 DetailSmoothMapSlope; /*RW; Range: [0x0, 0x400]*/
	CVI_U8 LumaWgt; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SharpenGain; /*RW; Range: [0x0, 0xff]*/
} ISP_DEMOSAIC_DEMOIRE_MANUAL_ATTR_S;

typedef struct _ISP_DEMOSAIC_DEMOIRE_AUTO_ATTR_S {
	CVI_U8 AntiFalseColorStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 SatGainIn[2][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 SatGainOut[2][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 ProtectColorGainIn[2][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 ProtectColorGainOut[2][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 UserDefineProtectColor1[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 UserDefineProtectColor2[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 UserDefineProtectColor3[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 EdgeGainIn[2][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 EdgeGainOut[2][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 DetailGainIn[2][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 DetailGaintOut[2][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U16 DetailDetectLumaStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xfff]*/
	CVI_U8 DetailSmoothStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 DetailWgtThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 DetailWgtMin[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x100]*/
	CVI_U16 DetailWgtMax[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x100]*/
	CVI_U16 DetailWgtSlope[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x400]*/
	CVI_U8 EdgeWgtNp[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EdgeWgtThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 EdgeWgtMin[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x100]*/
	CVI_U16 EdgeWgtMax[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x100]*/
	CVI_U16 EdgeWgtSlope[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x400]*/
	CVI_U8 DetailSmoothMapTh[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 DetailSmoothMapMin[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x100]*/
	CVI_U16 DetailSmoothMapMax[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x100]*/
	CVI_U16 DetailSmoothMapSlope[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x400]*/
	CVI_U8 LumaWgt[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SharpenGain[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
} ISP_DEMOSAIC_DEMOIRE_AUTO_ATTR_S;

typedef struct _ISP_DEMOSAIC_DEMOIRE_ATTR_S {
	CVI_BOOL AntiFalseColorEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL ProtectColorEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL DetailDetectLumaEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL DetailSmoothEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL DetailMode; /*RW; Range: [0x0, 0x1]*/
	ISP_DEMOSAIC_DEMOIRE_MANUAL_ATTR_S stManual;
	ISP_DEMOSAIC_DEMOIRE_AUTO_ATTR_S stAuto;
} ISP_DEMOSAIC_DEMOIRE_ATTR_S;
//--------------------------------------------------------------------------------
// DEMOSAIC >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// PRESHARPEN <<<<<<<<
//--------------------------------------------------------------------------------
#define SHARPEN_LUT_NUM (33)
#define EE_LUT_NODE (4)
#define PRE_EE_REFINE_LUT_NUM (8)

typedef enum _ISP_REFINE_TYPE_E {
	OP_TYPE_EDGE,
	OP_TYPE_CONTRAST,
	OP_TYPE_AVERAGE,
} ISP_REFINE_TYPE_E;

typedef struct _ISP_PRESHARPEN_MANUAL_ATTR_S {
	CVI_U16 FlatThr; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 EdgeThr; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 FlatThrHLD; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 EdgeThrHLD; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 LumaThrHLD; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U8 ThinStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 RobustStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 FlatStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EdgeStr; /*RW; Range: [0x0, 0xff]*/
	CVI_S16 StrFlatSlope; /*RW; Range: [-0x8000, 0x7fff]*/
	CVI_S16 StrEdgeSlope; /*RW; Range: [-0x8000, 0x7fff]*/
	CVI_U8 ConEngBlendWt; /*RW; Range: [0x0, 0xf]*/
	CVI_U16 EdgeLowEndThr; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 EdgeMidEndThr; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 EdgeHighEndThr; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U8 HueShtCtrl[SHARPEN_LUT_NUM]; /*RW; Range: [0x0, 0x3f]*/
	CVI_U8 SatShtGainIn[EE_LUT_NODE]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SatShtGainOut[EE_LUT_NODE]; /*RW; Range: [0x0, 0x80]*/
} ISP_PRESHARPEN_MANUAL_ATTR_S;

typedef struct _ISP_PRESHARPEN_AUTO_ATTR_S {
	CVI_U16 FlatThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 EdgeThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 FlatThrHLD[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 EdgeThrHLD[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 LumaThrHLD[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U8 ThinStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 RobustStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 FlatStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EdgeStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_S16 StrFlatSlope[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [-0x8000, 0x7fff]*/
	CVI_S16 StrEdgeSlope[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [-0x8000, 0x7fff]*/
	CVI_U8 ConEngBlendWt[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xf]*/
	CVI_U16 EdgeLowEndThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 EdgeMidEndThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 EdgeHighEndThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U8 HueShtCtrl[SHARPEN_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3f]*/
	CVI_U8 SatShtGainIn[EE_LUT_NODE][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SatShtGainOut[EE_LUT_NODE][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x80]*/
} ISP_PRESHARPEN_AUTO_ATTR_S;

typedef struct _ISP_PRESHARPEN_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x1, 0xff]*/
	CVI_U8 TuningMode; /*RW; Range: [0x0, 0xf]*/
	CVI_BOOL GammaSelection; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL ChnSelection; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL ParamAutoEn; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL SatShtCtrlEn; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL EdgeOutFormat; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 ReduceByEvRatioThr; /*RW; Range: [0x40, 0xff]*/
	CVI_U8 ReduceByEvRatioStr; /*RW; Range: [0x0, 0xff]*/
	ISP_PRESHARPEN_MANUAL_ATTR_S stManual;
	ISP_PRESHARPEN_AUTO_ATTR_S stAuto;
} ISP_PRESHARPEN_ATTR_S;

typedef struct _ISP_PRESHARPEN_REFINE_MANUAL_ATTR_S {
	CVI_U16 LumaLowThr; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 LumaHighThr; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U8 LumaLowStep; /*RW; Range: [0x0, 0x7]*/
	CVI_U8 LumaHighStep; /*RW; Range: [0x0, 0x7]*/
	CVI_U8 LumaLowLut[PRE_EE_REFINE_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 LumaHighLut[PRE_EE_REFINE_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 EdgeLowThr; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 EdgeHighThr; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U8 EdgeLowStep; /*RW; Range: [0x0, 0x7]*/
	CVI_U8 EdgeHighStep; /*RW; Range: [0x0, 0x7]*/
	CVI_U8 EdgeLowLut[PRE_EE_REFINE_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EdgeHighLut[PRE_EE_REFINE_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 OvershootThr; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 OshootSlope; /*RW; Range: [0x0, 0x7fff]*/
	CVI_U16 OshootWgtHigh; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UndershootThr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootSlope; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootWgtHigh; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootLumThrLow; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootLumThrHigh; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootLumClampWgt; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootEngThrLow; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootEngThrHigh; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootEngClampWgt; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootLumEngStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootLumEngNorm; /*RW; Range: [0x0, 0xff]*/
} ISP_PRESHARPEN_REFINE_MANUAL_ATTR_S;

typedef struct _ISP_PRESHARPEN_REFINE_AUTO_ATTR_S {
	CVI_U16 LumaLowThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 LumaHighThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U8 LumaLowStep[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x7]*/
	CVI_U8 LumaHighStep[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x7]*/
	CVI_U8 LumaLowLut[PRE_EE_REFINE_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 LumaHighLut[PRE_EE_REFINE_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 EdgeLowThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 EdgeHighThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U8 EdgeLowStep[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x7]*/
	CVI_U8 EdgeHighStep[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x7]*/
	CVI_U8 EdgeLowLut[PRE_EE_REFINE_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EdgeHighLut[PRE_EE_REFINE_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 OvershootThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 OshootSlope[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x7fff]*/
	CVI_U16 OshootWgtHigh[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UndershootThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootSlope[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootWgtHigh[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootLumThrLow[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootLumThrHigh[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootLumClampWgt[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootEngThrLow[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootEngThrHigh[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootEngClampWgt[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootLumEngStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UshootLumEngNorm[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
} ISP_PRESHARPEN_REFINE_AUTO_ATTR_S;

typedef struct _ISP_PRESHARPEN_REFINE_ATTR_S {
	CVI_BOOL OverUnderShootEn; /*RW; Range: [0x0, 0x1]*/
	ISP_REFINE_TYPE_E RefineEdgeType; /*RW; Range: [0x0, 0x2]*/
	ISP_PRESHARPEN_REFINE_MANUAL_ATTR_S stManual;
	ISP_PRESHARPEN_REFINE_AUTO_ATTR_S stAuto;
} ISP_PRESHARPEN_REFINE_ATTR_S;

typedef struct _ISP_PRESHARPEN_EDGE_EXT_MANUAL_ATTR_S {
	CVI_U16 E5aEnhance; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 E5bEnhance; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 E5cEnhance; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 E7Enhance; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U8 BlendThrLow; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 BlendThrHigh; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 BlendWgtLow; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 BlendWgtHigh; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 ThinWgtFlat; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 ThinWgtEdge; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 ThinWgtUHF_HF; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 RobustWgtHF_SHF; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 ThinWgtAgainstSHF; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 RobustWgtAgainstMF; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 ThinWgtFlatHLD; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 ThinWgtEdgeHLD; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 ThinWgtUHF_HF_HLD; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 RobustWgtHF_SHF_HLD; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 ThinWgtAgainstSHF_HLD; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 RobustWgtAgainstMF_HLD; /*RW; Range: [0x0, 0x8]*/
} ISP_PRESHARPEN_EDGE_EXT_MANUAL_ATTR_S;

typedef struct _ISP_PRESHARPEN_EDGE_EXT_AUTO_ATTR_S {
	CVI_U16 E5aEnhance[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 E5bEnhance[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 E5cEnhance[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 E7Enhance[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U8 BlendThrLow[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 BlendThrHigh[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 BlendWgtLow[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 BlendWgtHigh[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 ThinWgtFlat[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 ThinWgtEdge[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 ThinWgtUHF_HF[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 RobustWgtHF_SHF[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 ThinWgtAgainstSHF[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 RobustWgtAgainstMF[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 ThinWgtFlatHLD[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 ThinWgtEdgeHLD[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 ThinWgtUHF_HF_HLD[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 RobustWgtHF_SHF_HLD[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 ThinWgtAgainstSHF_HLD[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 RobustWgtAgainstMF_HLD[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x8]*/
} ISP_PRESHARPEN_EDGE_EXT_AUTO_ATTR_S;

typedef struct _ISP_PRESHARPEN_EDGE_EXT_ATTR_S {
	CVI_BOOL RegionStrEn; /*RW; Range: [0x0, 0x1]*/
	ISP_PRESHARPEN_EDGE_EXT_MANUAL_ATTR_S stManual;
	ISP_PRESHARPEN_EDGE_EXT_AUTO_ATTR_S stAuto;
} ISP_PRESHARPEN_EDGE_EXT_ATTR_S;
//--------------------------------------------------------------------------------
// PRESHARPEN >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// PFR <<<<<<<<
//--------------------------------------------------------------------------------
#define PFR_COLOR_NUM (2)
#define PFR_COLOR_LUT_NUM (5)
#define PFR_EDGE_LUT_NUM (4)
#define PFR_LUMA_LEVEL (17)

typedef struct _ISP_PFR_MANUAL_ATTR_S {
	CVI_U8 LumaIniVal; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 LumLevelTh; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 LumLevelLut[PFR_LUMA_LEVEL]; /*RW; Range: [0x0, 0xff]*/
} ISP_PFR_MANUAL_ATTR_S;

typedef struct _ISP_PFR_AUTO_ATTR_S {
	CVI_U8 LumaIniVal[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 LumLevelTh[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 LumLevelLut[PFR_LUMA_LEVEL][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
} ISP_PFR_AUTO_ATTR_S;

typedef struct _ISP_PFR_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
	CVI_BOOL TuningMode; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL LumaEN; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL UVENLut[PFR_COLOR_NUM]; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL HueENLut[PFR_COLOR_NUM]; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 ULut[PFR_COLOR_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 VLut[PFR_COLOR_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UVDiffThLut[PFR_COLOR_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UVDiffLut0[PFR_COLOR_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UVDiffLut1[PFR_COLOR_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 RWetLut[PFR_COLOR_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 BWetLut[PFR_COLOR_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 HueLut[PFR_COLOR_NUM]; /*RW; Range: [0x0, 0x167]*/
	CVI_U8 HueRngLut[PFR_COLOR_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 HueTh; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EdgeThLut[PFR_EDGE_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 GDiffLut[PFR_COLOR_LUT_NUM]; /*RW; Range: [0x0, 0x7f]*/
	ISP_PFR_MANUAL_ATTR_S stManual;
	ISP_PFR_AUTO_ATTR_S stAuto;
} ISP_PFR_ATTR_S;
//--------------------------------------------------------------------------------
// PFR >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// CCM <<<<<<<<
//--------------------------------------------------------------------------------
typedef struct _ISP_CCM_MANUAL_ATTR_S {
	CVI_BOOL SatEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_S16 CCM[9]; /*RW; Range: [-0x2000, 0x1fff]*/
} ISP_CCM_MANUAL_ATTR_S;

typedef struct _ISP_COLORMATRIX_ATTR_S {
	CVI_U16 ColorTemp; /*RW; Range: [0x1f4, 0x7530]*/
	CVI_S16 CCM[9]; /*RW; Range: [-0x2000, 0x1fff]*/
} ISP_COLORMATRIX_ATTR_S;

typedef struct _ISP_CCM_AUTO_ATTR_S {
	CVI_BOOL ISOActEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL TempActEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 CCMTabNum; /*RW; Range: [0x3, 0x7]*/
	ISP_COLORMATRIX_ATTR_S CCMTab[7];
} ISP_CCM_AUTO_ATTR_S;

typedef struct _ISP_CCM_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 CCMOverStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 CCMOverThr; /*RW; Range: [0x0, 0xff]*/
	ISP_CCM_MANUAL_ATTR_S stManual;
	ISP_CCM_AUTO_ATTR_S stAuto;
} ISP_CCM_ATTR_S;

typedef struct _ISP_CCM_SATURATION_MANUAL_ATTR_S {
	CVI_U8 SaturationLE; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SaturationSE; /*RW; Range: [0x0, 0xff]*/
} ISP_CCM_SATURATION_MANUAL_ATTR_S;

typedef struct _ISP_CCM_SATURATION_AUTO_ATTR_S {
	CVI_U8 SaturationLE[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SaturationSE[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
} ISP_CCM_SATURATION_AUTO_ATTR_S;

typedef struct _ISP_CCM_SATURATION_ATTR_S {
	ISP_CCM_SATURATION_MANUAL_ATTR_S stManual;
	ISP_CCM_SATURATION_AUTO_ATTR_S stAuto;
} ISP_CCM_SATURATION_ATTR_S;

typedef struct _ISP_SATURATION_MANUAL_ATTR_S {
	CVI_U8 Saturation; /*RW; Range: [0x0, 0xff]*/
} ISP_SATURATION_MANUAL_ATTR_S;

typedef struct _ISP_SATURATION_AUTO_ATTR_S {
	CVI_U8 Saturation[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
} ISP_SATURATION_AUTO_ATTR_S;

typedef struct _ISP_SATURATION_ATTR_S {
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	ISP_SATURATION_MANUAL_ATTR_S stManual;
	ISP_SATURATION_AUTO_ATTR_S stAuto;
} ISP_SATURATION_ATTR_S;
//--------------------------------------------------------------------------------
// CCM >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// RGBGAMMA <<<<<<<<
//--------------------------------------------------------------------------------
#define GAMMA_NODE_NUM (256)

typedef enum _ISP_GAMMA_CURVE_TYPE_E {
	ISP_GAMMA_CURVE_DEFAULT,
	ISP_GAMMA_CURVE_SRGB,
	ISP_GAMMA_CURVE_USER_DEFINE,
	ISP_GAMMA_CURVE_BYPASS,
	ISP_GAMMA_CURVE_MAX,
} ISP_GAMMA_CURVE_TYPE_E;

typedef struct _ISP_GAMMA_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 Table[GAMMA_NODE_NUM]; /*RW; Range: [0x0, 0xfff]*/
	ISP_GAMMA_CURVE_TYPE_E enCurveType; /*RW; Range: [0x0, 0x4]*/
} ISP_GAMMA_ATTR_S;
//--------------------------------------------------------------------------------
// RGBGAMMA >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// CLUT <<<<<<<<
//--------------------------------------------------------------------------------
#define ISP_CLUT_LUT_LENGTH (4913)
#define ISP_CLUT_HUE_LENGTH (37)
#define ISP_CLUT_SAT_LENGTH (21)

typedef struct _ISP_CLUT_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 ClutR[ISP_CLUT_LUT_LENGTH]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 ClutG[ISP_CLUT_LUT_LENGTH]; /*RW; Range: [0x0, 0x3ff]*/
	CVI_U16 ClutB[ISP_CLUT_LUT_LENGTH]; /*RW; Range: [0x0, 0x3ff]*/
} ISP_CLUT_ATTR_S;

typedef struct _ISP_CLUT_HSL_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	CVI_FLOAT Sigma; /*RW; Range: [0x0, 0x40]*/
	CVI_S16 HByH[ISP_CLUT_HUE_LENGTH]; /*RW; Range: [-0x1e, 0x1e]*/
	CVI_U16 SByH[ISP_CLUT_HUE_LENGTH]; /*RW; Range: [0x0, 0x64]*/
	CVI_U16 LByH[ISP_CLUT_HUE_LENGTH]; /*RW; Range: [0x0, 0x64]*/
	CVI_U16 SByS[ISP_CLUT_SAT_LENGTH]; /*RW; Range: [0x0, 0x64]*/
} ISP_CLUT_HSL_ATTR_S;
//--------------------------------------------------------------------------------
// CLUT >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// CSC <<<<<<<<
//--------------------------------------------------------------------------------
#define CSC_MATRIX_SIZE (9)
#define CSC_OFFSET_SIZE (3)

typedef enum _ISP_CSC_COLORGAMUT {
	ISP_CSC_COLORGAMUT_BT601,
	ISP_CSC_COLORGAMUT_BT709,
	ISP_CSC_COLORGAMUT_BT2020,
	ISP_CSC_COLORGAMUT_USER,
	ISP_CSC_COLORGAMUT_NUM,
} ISP_CSC_COLORGAMUT;

typedef struct _ISP_CSC_MATRX_S {
	CVI_S16 userCscCoef[CSC_MATRIX_SIZE]; /*RW; Range: [-0x2000, 0x1fff]*/
	CVI_S16 userCscOffset[CSC_OFFSET_SIZE]; /*RW; Range: [-0x100, 0xff]*/
} ISP_CSC_MATRX_S;

typedef struct _ISP_CSC_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_CSC_COLORGAMUT enColorGamut; /*RW; Range: [0x0, 0x4]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 Hue; /*RW; Range: [0x0, 0x64]*/
	CVI_U8 Luma; /*RW; Range: [0x0, 0x64]*/
	CVI_U8 Contrast; /*RW; Range: [0x0, 0x64]*/
	CVI_U8 Saturation; /*RW; Range: [0x0, 0x64]*/
	ISP_CSC_MATRX_S stUserMatrx;
} ISP_CSC_ATTR_S;
//--------------------------------------------------------------------------------
// CSC >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// DCI <<<<<<<<
//--------------------------------------------------------------------------------
#define DCI_GAMMA_MAX_NUM (5)
#define DCI_DEHAZE_LUT_NUM (6)
#define DCI_GAMMA_NODE_NUM (256)

typedef enum _ISP_DCI_CURVE_MODE_E {
	DCI_CURVE_AUTO,
	DCI_CURVE_AUTO_GAMMA,
	DCI_CURVE_DEHAZE,
} ISP_DCI_CURVE_MODE_E;

typedef struct _ISP_DCI_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_DCI_CURVE_MODE_E CurveMode; /*RW; Range: [0x0, 0x2]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x1, 0xff]*/
	CVI_U16 DciStrength; /*RW; Range: [0x0, 0x2000]*/
	CVI_U8 DciGamma[DCI_GAMMA_MAX_NUM]; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 DciContrast[DCI_GAMMA_MAX_NUM]; /*RW; Range: [0x0, 0x3]*/
	CVI_U8 DciOffset[DCI_GAMMA_MAX_NUM]; /*RW; Range: [0x0, 0xf]*/
	CVI_U8 Sensitivity; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 Speed; /*RW; Range: [0x0, 0x1f4]*/
	CVI_U8 DehazeLight; /*RW; Range: [0x0, 0x5]*/
	CVI_U8 DehazeStrength; /*RW; Range: [0x0, 0x64]*/
	CVI_U8 DehazeLut[DCI_DEHAZE_LUT_NUM]; /*RW; Range: [0x0, 0x64]*/
} ISP_DCI_ATTR_S;

typedef struct _ISP_DCI_GAMMA_CURVE_ATTR_S {
	CVI_S16 Lv; /*RW; Range: [-0x1f4, 0x5dc]*/
	CVI_U16 Tbl[DCI_GAMMA_NODE_NUM]; /*RW; Range: [0x0, 0xff]*/
} ISP_DCI_GAMMA_CURVE_ATTR_S;

typedef struct _ISP_DCI_AUTO_GAMMA_ATTR_S {
	CVI_U8 GammaTabNum; /*RW; Range: [0x1, 0x5]*/
	ISP_DCI_GAMMA_CURVE_ATTR_S GammaTab[DCI_GAMMA_MAX_NUM];
} ISP_DCI_AUTO_GAMMA_ATTR_S;
//--------------------------------------------------------------------------------
// DCI >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// LDCI <<<<<<<<
//--------------------------------------------------------------------------------
typedef struct _ISP_LDCI_MANUAL_ATTR_S {
	CVI_U8 LdciStrength[9]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 AdaptiveGainMax; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 AdaptiveGainMin; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 FBCStrength; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 LdciThres1; /*RW; Range: [0x0, 0xff]*/
} ISP_LDCI_MANUAL_ATTR_S;

typedef struct _ISP_LDCI_AUTO_ATTR_S {
	CVI_U8 LdciStrength[9][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 AdaptiveGainMax[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 AdaptiveGainMin[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 FBCStrength[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 LdciThres1[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
} ISP_LDCI_AUTO_ATTR_S;

typedef struct _ISP_LDCI_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 BlockNum; /*RW; Range: [0x4, 0x3e]*/
	ISP_LDCI_MANUAL_ATTR_S stManual;
	ISP_LDCI_AUTO_ATTR_S stAuto;
} ISP_LDCI_ATTR_S;
//--------------------------------------------------------------------------------
// LDCI >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// TNR <<<<<<<<
//--------------------------------------------------------------------------------
#define TNR_STATUS_NUM (3)
#define TNR_ACBD_RANK (4)
#define TNR_LUMA_RANK (8)
#define TNR_STATUS_CHANGE (2)
#define TNR_FREQ_RANK (4)
#define TNR_DETAIL_RANK (8)

typedef struct _ISP_TNR_MANUAL_ATTR_S {
	CVI_U8 DyBlurStr; /*RW; Range: [0x0, 0x3]*/
	CVI_U8 DyBlurYWt[TNR_STATUS_NUM]; /*RW; Range: [0x0, 0xf]*/
} ISP_TNR_MANUAL_ATTR_S;

typedef struct _ISP_TNR_AUTO_ATTR_S {
	CVI_U8 DyBlurStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3]*/
	CVI_U8 DyBlurYWt[TNR_STATUS_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xf]*/
} ISP_TNR_AUTO_ATTR_S;

typedef struct _ISP_TNR_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 updateInterval; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 DbgMode; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 DyBlurUVWt; /*RW; Range: [0x0, 0xf]*/
	CVI_U8 DyBlurJndTh; /*RW; Range: [0x0, 0x1f]*/
	ISP_TNR_MANUAL_ATTR_S stManual;
	ISP_TNR_AUTO_ATTR_S stAuto;
} ISP_TNR_ATTR_S;

typedef struct _ISP_TNR_MV_MANUAL_ATTR_S {
	CVI_U8 StableIntensity; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 L0YPSSBlur; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 AcbdSadAdj[TNR_ACBD_RANK]; /*RW; Range: [0x0, 0x3fff]*/
	CVI_U8 AcbdEdgeAdj[TNR_ACBD_RANK]; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 LumaJndTh[TNR_LUMA_RANK]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 LumaJndRatio; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 JndSadWt; /*RW; Range: [0x0, 0xf]*/
	CVI_U16 WarpB0[TNR_LUMA_RANK]; /*RW; Range: [0x0, 0x3fff]*/
	CVI_U8 WarpEdge[TNR_LUMA_RANK]; /*RW; Range: [0x0, 0x3f]*/
	CVI_U16 WarpBase[TNR_LUMA_RANK]; /*RW; Range: [0x0, 0x3fff]*/
	CVI_U16 WarpStd[TNR_LUMA_RANK]; /*RW; Range: [0x0, 0x3fff]*/
} ISP_TNR_MV_MANUAL_ATTR_S;

typedef struct _ISP_TNR_MV_AUTO_ATTR_S {
	CVI_U8 StableIntensity[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 L0YPSSBlur[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 AcbdSadAdj[TNR_ACBD_RANK][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3fff]*/
	CVI_U8 AcbdEdgeAdj[TNR_ACBD_RANK][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 LumaJndTh[TNR_LUMA_RANK][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 LumaJndRatio[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 JndSadWt[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xf]*/
	CVI_U16 WarpB0[TNR_LUMA_RANK][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3fff]*/
	CVI_U8 WarpEdge[TNR_LUMA_RANK][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3f]*/
	CVI_U16 WarpBase[TNR_LUMA_RANK][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3fff]*/
	CVI_U16 WarpStd[TNR_LUMA_RANK][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3fff]*/
} ISP_TNR_MV_AUTO_ATTR_S;

typedef struct _ISP_TNR_MV_ATTR_S {
	CVI_BOOL NullFlowEn; /*RW; Range: [0x0, 0x1]*/
	ISP_TNR_MV_MANUAL_ATTR_S stManual;
	ISP_TNR_MV_AUTO_ATTR_S stAuto;
} ISP_TNR_MV_ATTR_S;

typedef struct _ISP_TNR_PS_MANUAL_ATTR_S {
	CVI_U8 JndStdRange[TNR_STATUS_CHANGE]; /*RW; Range: [0x0, 0x20]*/
	CVI_U8 WarpStdRange[TNR_STATUS_CHANGE]; /*RW; Range: [0x0, 0x20]*/
	CVI_U8 NbrBldRatio[TNR_STATUS_CHANGE]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 StillRegionTh[TNR_STATUS_CHANGE]; /*RW; Range: [0x0, 0xffff]*/
	CVI_U8 FlowJndTh; /*RW; Range: [0x0, 0x3f]*/
} ISP_TNR_PS_MANUAL_ATTR_S;

typedef struct _ISP_TNR_PS_AUTO_ATTR_S {
	CVI_U8 JndStdRange[TNR_STATUS_CHANGE][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x20]*/
	CVI_U8 WarpStdRange[TNR_STATUS_CHANGE][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x20]*/
	CVI_U8 NbrBldRatio[TNR_STATUS_CHANGE][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 StillRegionTh[TNR_STATUS_CHANGE][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xffff]*/
	CVI_U8 FlowJndTh[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3f]*/
} ISP_TNR_PS_AUTO_ATTR_S;

typedef struct _ISP_TNR_PS_ATTR_S {
	CVI_BOOL SadDebiasEN; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 SadLpfMode; /*RW; Range: [0x0, 0x3]*/
	ISP_TNR_PS_MANUAL_ATTR_S stManual;
	ISP_TNR_PS_AUTO_ATTR_S stAuto;
} ISP_TNR_PS_ATTR_S;

typedef struct _ISP_TNR_NR_MANUAL_ATTR_S {
	CVI_U8 L0YBlurStr[TNR_STATUS_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L0YSigmaStr[TNR_STATUS_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L0UVSigmaStr[TNR_STATUS_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 L0YGardBlurTh; /*RW; Range: [0x0, 0xffff]*/
	CVI_U8 L0YGardBlurStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L1PFTStr[TNR_FREQ_RANK]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 L1SpaGlobalStr; /*RW; Range: [0x0, 0xffff]*/
	CVI_U16 L1TmpGlobalStr; /*RW; Range: [0x0, 0xffff]*/
	CVI_U8 L1LumaAdj[TNR_LUMA_RANK]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L1FSJndAdj[TNR_STATUS_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L1FTJndAdj[TNR_STATUS_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L1FSFreAdj[TNR_FREQ_RANK]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L1FTFreAdj[TNR_FREQ_RANK]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L1FTLumaStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L1PFTDamp[TNR_STATUS_CHANGE]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L2YDampStr[TNR_STATUS_CHANGE]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L2YLut[TNR_DETAIL_RANK]; /*RW; Range: [0x0, 0x7f]*/
	CVI_U8 L2UVDampStr[TNR_STATUS_CHANGE]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L2UVLut[TNR_DETAIL_RANK]; /*RW; Range: [0x0, 0x7f]*/
} ISP_TNR_NR_MANUAL_ATTR_S;

typedef struct _ISP_TNR_NR_AUTO_ATTR_S {
	CVI_U8 L0YBlurStr[TNR_STATUS_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L0YSigmaStr[TNR_STATUS_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L0UVSigmaStr[TNR_STATUS_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 L0YGardBlurTh[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xffff]*/
	CVI_U8 L0YGardBlurStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L1PFTStr[TNR_FREQ_RANK][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U16 L1SpaGlobalStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xffff]*/
	CVI_U16 L1TmpGlobalStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xffff]*/
	CVI_U8 L1LumaAdj[TNR_LUMA_RANK][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L1FSJndAdj[TNR_STATUS_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L1FTJndAdj[TNR_STATUS_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L1FSFreAdj[TNR_FREQ_RANK][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L1FTFreAdj[TNR_FREQ_RANK][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L1FTLumaStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L1PFTDamp[TNR_STATUS_CHANGE][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L2YDampStr[TNR_STATUS_CHANGE][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L2YLut[TNR_DETAIL_RANK][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x7f]*/
	CVI_U8 L2UVDampStr[TNR_STATUS_CHANGE][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 L2UVLut[TNR_DETAIL_RANK][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x7f]*/
} ISP_TNR_NR_AUTO_ATTR_S;

typedef struct _ISP_TNR_NR_ATTR_S {
	CVI_BOOL L12NrYEN; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL L2UVNrEN; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL L2UVMonoEN; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL DcEn; /*RW; Range: [0x0, 0x1]*/
	ISP_TNR_NR_MANUAL_ATTR_S stManual;
	ISP_TNR_NR_AUTO_ATTR_S stAuto;
} ISP_TNR_NR_ATTR_S;
//--------------------------------------------------------------------------------
// TNR >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// CNR <<<<<<<<
//--------------------------------------------------------------------------------
#define CNR_MOTION_LUT_NUM (3)
#define CNR_REFCTHR_LUT_NUM (3)
#define CNR_REFCSTR_LUT_NUM (4)
#define CNR_FLTTHR_LUT_NUM (5)
#define CNR_FLTSTR_LUT_NUM (6)

typedef enum _ISP_CNR_SCALE_FACTOR_E {
	SCALE_FACTOR_4,
	SCALE_FACTOR_8,
	SCALE_FACTOR_16,
} ISP_CNR_SCALE_FACTOR_E;

typedef struct _ISP_CNR_MANUAL_ATTR_S {
	CVI_U8 MedianFltKsize; /*RW; Range: [0x0, 0x2]*/
	CVI_U8 CnrByMotion[CNR_MOTION_LUT_NUM]; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 CnrRefYStr; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 CnrRefUVStr; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 CnrYRange; /*RW; Range: [0x0, 0x3]*/
	CVI_U8 CnrYThr; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 CnrYPrcStr; /*RW; Range: [0x0, 0x2]*/
	CVI_U8 CnrYStrH; /*RW; Range: [0x0, 0x20]*/
	CVI_U8 CnrYStrT; /*RW; Range: [0x0, 0x20]*/
	CVI_U8 CnrUVRange; /*RW; Range: [0x0, 0x4]*/
	CVI_U8 CnrUVThr; /*RW; Range: [0x0, 0x20]*/
	CVI_U8 CnrUVPrcStr; /*RW; Range: [0x0, 0x3]*/
	CVI_U8 CnrUVStrH; /*RW; Range: [0x0, 0x40]*/
	CVI_U8 CnrUVStrT; /*RW; Range: [0x0, 0x40]*/
	CVI_U8 CnrSatRange; /*RW; Range: [0x0, 0x3]*/
	CVI_U8 CnrSatPrtThr; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 CnrSatPrcStr; /*RW; Range: [0x0, 0x2]*/
	CVI_U8 CnrSatStrH; /*RW; Range: [0x0, 0x20]*/
	CVI_U8 CnrSatStrT; /*RW; Range: [0x0, 0x20]*/
	CVI_U8 CnrSatBldCoring; /*RW; Range: [0x0, 0x20]*/
} ISP_CNR_MANUAL_ATTR_S;

typedef struct _ISP_CNR_AUTO_ATTR_S {
	CVI_U8 MedianFltKsize[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x2]*/
	CVI_U8 CnrByMotion[CNR_MOTION_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 CnrRefYStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 CnrRefUVStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 CnrYRange[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3]*/
	CVI_U8 CnrYThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 CnrYPrcStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x2]*/
	CVI_U8 CnrYStrH[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x20]*/
	CVI_U8 CnrYStrT[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x20]*/
	CVI_U8 CnrUVRange[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x4]*/
	CVI_U8 CnrUVThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x20]*/
	CVI_U8 CnrUVPrcStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3]*/
	CVI_U8 CnrUVStrH[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x40]*/
	CVI_U8 CnrUVStrT[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x40]*/
	CVI_U8 CnrSatRange[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3]*/
	CVI_U8 CnrSatPrtThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 CnrSatPrcStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x2]*/
	CVI_U8 CnrSatStrH[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x20]*/
	CVI_U8 CnrSatStrT[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x20]*/
	CVI_U8 CnrSatBldCoring[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x20]*/
} ISP_CNR_AUTO_ATTR_S;

typedef struct _ISP_CNR_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x1, 0xff]*/
	CVI_BOOL MedianFltEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL CnrEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL CnrSatBldEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 SubSclSel; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 CnrDebugMode; /*RW; Range: [0x0, 0x6]*/
	CVI_BOOL CnrBypass1; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL CnrBypass2; /*RW; Range: [0x0, 0x1]*/
	ISP_CNR_SCALE_FACTOR_E SubImgSclFactor; /*RW; Range: [0x0, 0x2]*/
	ISP_CNR_MANUAL_ATTR_S stManual;
	ISP_CNR_AUTO_ATTR_S stAuto;
} ISP_CNR_ATTR_S;

typedef struct _ISP_CNR_FILTER_MANUAL_ATTR_S {
	CVI_U8 SubImgNrFltKsize; /*RW; Range: [0x0, 0x3]*/
	CVI_U8 SubImgNrEdgeDirPN; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrEdgeDirHV; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrEdgeKsize; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 SubImgNrYCRef; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 SubImgNrUVCRef; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 OutierThY; /*RW; Range: [0x0, 0x7]*/
	CVI_U8 OutierThUV; /*RW; Range: [0x0, 0x7]*/
	CVI_U8 YOutierDifTh; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UOutierDifTh; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 VOutierDifTh; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrRefCThrYDif[CNR_REFCTHR_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrRefCStrY[CNR_REFCSTR_LUT_NUM]; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 SubImgNrRefCThrUVDif[CNR_REFCTHR_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrRefCStrUV[CNR_REFCSTR_LUT_NUM]; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 SubImgNrDirFltThrY[CNR_FLTTHR_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrDirFltStrY[CNR_FLTSTR_LUT_NUM]; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 SubImgNrDirFltThrU[CNR_FLTTHR_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrDirFltStrU[CNR_FLTSTR_LUT_NUM]; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 SubImgNrDirFltThrV[CNR_FLTTHR_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrDirFltStrV[CNR_FLTSTR_LUT_NUM]; /*RW; Range: [0x0, 0x10]*/
} ISP_CNR_FILTER_MANUAL_ATTR_S;

typedef struct _ISP_CNR_FILTER_AUTO_ATTR_S {
	CVI_U8 SubImgNrFltKsize[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3]*/
	CVI_U8 SubImgNrEdgeDirPN[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrEdgeDirHV[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrEdgeKsize[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 SubImgNrYCRef[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 SubImgNrUVCRef[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x1f]*/
	CVI_U8 OutierThY[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x7]*/
	CVI_U8 OutierThUV[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x7]*/
	CVI_U8 YOutierDifTh[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UOutierDifTh[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 VOutierDifTh[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrRefCThrYDif[CNR_REFCTHR_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrRefCStrY[CNR_REFCSTR_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 SubImgNrRefCThrUVDif[CNR_REFCTHR_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrRefCStrUV[CNR_REFCSTR_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x8]*/
	CVI_U8 SubImgNrDirFltThrY[CNR_FLTTHR_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrDirFltStrY[CNR_FLTSTR_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 SubImgNrDirFltThrU[CNR_FLTTHR_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrDirFltStrU[CNR_FLTSTR_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x10]*/
	CVI_U8 SubImgNrDirFltThrV[CNR_FLTTHR_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SubImgNrDirFltStrV[CNR_FLTSTR_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x10]*/
} ISP_CNR_FILTER_AUTO_ATTR_S;

typedef struct _ISP_CNR_FILTER_ATTR_S {
	CVI_BOOL SubImgNrEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL YNrEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL EdgeDebugEnable; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL RefCenterDebugEnable; /*RW; Range: [0x0, 0x1]*/
	ISP_CNR_FILTER_MANUAL_ATTR_S stManual;
	ISP_CNR_FILTER_AUTO_ATTR_S stAuto;
} ISP_CNR_FILTER_ATTR_S;
//--------------------------------------------------------------------------------
// CNR >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// SHARPEN <<<<<<<<
//--------------------------------------------------------------------------------
#define EE_NOISE_LUT_NUM (17)
#define SHARPEN_LUT_NUM (33)
#define EE_LUT_NODE (4)

typedef enum _ISP_EE_FILTER_SIZE_TYPE_E {
	OP_TYPE_3x3,
	OP_TYPE_5x5,
} ISP_EE_FILTER_SIZE_TYPE_E;

typedef enum _ISP_EE_WEIGHT_SRC_TYPE_E {
	OP_TYPE_Y,
	OP_TYPE_DEGAMMA_Y,
} ISP_EE_WEIGHT_SRC_TYPE_E;

typedef struct _ISP_SHARPEN_MANUAL_ATTR_S {
	CVI_U8 EE1CoringThr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 NoiseBase; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE2BalanceRatio; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE2SharpStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE2CoringThr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 OverShootRatio; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UnderShootRatio; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE1BlendWgt; /*RW; Range: [0x0, 0x8]*/
	CVI_U16 EE1FlatThr; /*RW; Range: [0x0, 0x7ff]*/
	CVI_U16 EE1EdgeThr; /*RW; Range: [0x0, 0x7ff]*/
	CVI_U8 EE1FlatRegionStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE1EdgeRegionStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE1MotionStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE1StaticStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE1TransStr; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 NoiseLut[EE_NOISE_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 HueShtCtrl[SHARPEN_LUT_NUM]; /*RW; Range: [0x0, 0x3f]*/
	CVI_U8 SatShtGainIn[EE_LUT_NODE]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SatShtGainOut[EE_LUT_NODE]; /*RW; Range: [0x0, 0x80]*/
} ISP_SHARPEN_MANUAL_ATTR_S;

typedef struct _ISP_SHARPEN_AUTO_ATTR_S {
	CVI_U8 EE1CoringThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 NoiseBase[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE2BalanceRatio[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE2SharpStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE2CoringThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 OverShootRatio[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 UnderShootRatio[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE1BlendWgt[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x8]*/
	CVI_U16 EE1FlatThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x7ff]*/
	CVI_U16 EE1EdgeThr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x7ff]*/
	CVI_U8 EE1FlatRegionStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE1EdgeRegionStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE1MotionStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE1StaticStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 EE1TransStr[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 NoiseLut[EE_NOISE_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 HueShtCtrl[SHARPEN_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x3f]*/
	CVI_U8 SatShtGainIn[EE_LUT_NODE][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 SatShtGainOut[EE_LUT_NODE][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x80]*/
} ISP_SHARPEN_AUTO_ATTR_S;

typedef struct _ISP_SHARPEN_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x1, 0xff]*/
	CVI_U8 TuningMode; /*RW; Range: [0x0, 0x7]*/
	CVI_BOOL MotionEn; /*RW; Range: [0x0, 0x1]*/
	CVI_BOOL SatShtCtrlEn; /*RW; Range: [0x0, 0x1]*/
	ISP_EE_FILTER_SIZE_TYPE_E enFilterType; /*RW; Range: [0x0, 0x1]*/
	ISP_EE_WEIGHT_SRC_TYPE_E EE1SrcType; /*RW; Range: [0x0, 0x1]*/
	ISP_SHARPEN_MANUAL_ATTR_S stManual;
	ISP_SHARPEN_AUTO_ATTR_S stAuto;
} ISP_SHARPEN_ATTR_S;
//--------------------------------------------------------------------------------
// SHARPEN >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// CA <<<<<<<<
//--------------------------------------------------------------------------------
#define CA_LUT_NUM (256)

typedef struct _ISP_CA_MANUAL_ATTR_S {
	CVI_U16 ISORatio; /*RW; Range: [0x0, 0x7ff]*/
	CVI_U16 YRatioLut[CA_LUT_NUM]; /*RW; Range: [0x0, 0x7ff]*/
} ISP_CA_MANUAL_ATTR_S;

typedef struct _ISP_CA_AUTO_ATTR_S {
	CVI_U16 ISORatio[ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x7ff]*/
	CVI_U16 YRatioLut[CA_LUT_NUM][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x7ff]*/
} ISP_CA_AUTO_ATTR_S;

typedef struct _ISP_CA_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x1, 0xff]*/
	CVI_BOOL CaCpMode; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 CPLutY[CA_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 CPLutU[CA_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	CVI_U8 CPLutV[CA_LUT_NUM]; /*RW; Range: [0x0, 0xff]*/
	ISP_CA_MANUAL_ATTR_S stManual;
	ISP_CA_AUTO_ATTR_S stAuto;
} ISP_CA_ATTR_S;
//--------------------------------------------------------------------------------
// CA >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// CA2 <<<<<<<<
//--------------------------------------------------------------------------------
#define CA_LITE_NODE (6)

typedef struct _ISP_CA2_MANUAL_ATTR_S {
	CVI_U8 Ca2In[CA_LITE_NODE]; /*RW; Range: [0x0, 0xc0]*/
	CVI_U16 Ca2Out[CA_LITE_NODE]; /*RW; Range: [0x0, 0x7ff]*/
} ISP_CA2_MANUAL_ATTR_S;

typedef struct _ISP_CA2_AUTO_ATTR_S {
	CVI_U8 Ca2In[CA_LITE_NODE][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0xc0]*/
	CVI_U16 Ca2Out[CA_LITE_NODE][ISP_AUTO_ISO_STRENGTH_NUM]; /*RW; Range: [0x0, 0x7ff]*/
} ISP_CA2_AUTO_ATTR_S;

typedef struct _ISP_CA2_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x1, 0xff]*/
	ISP_CA2_MANUAL_ATTR_S stManual;
	ISP_CA2_AUTO_ATTR_S stAuto;
} ISP_CA2_ATTR_S;
//--------------------------------------------------------------------------------
// CA2 >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// YCONTRAST <<<<<<<<
//--------------------------------------------------------------------------------
typedef struct _ISP_YCONTRAST_MANUAL_ATTR_S {
	CVI_U8 ContrastLow; /*RW; Range: [0x0, 0x64]*/
	CVI_U8 ContrastHigh; /*RW; Range: [0x0, 0x64]*/
	CVI_U8 CenterLuma; /*RW; Range: [0x0, 0x40]*/
} ISP_YCONTRAST_MANUAL_ATTR_S;

typedef struct _ISP_YCONTRAST_AUTO_ATTR_S {
	CVI_U8 ContrastLow[ISP_AUTO_LV_NUM]; /*RW; Range: [0x0, 0x64]*/
	CVI_U8 ContrastHigh[ISP_AUTO_LV_NUM]; /*RW; Range: [0x0, 0x64]*/
	CVI_U8 CenterLuma[ISP_AUTO_LV_NUM]; /*RW; Range: [0x0, 0x40]*/
} ISP_YCONTRAST_AUTO_ATTR_S;

typedef struct _ISP_YCONTRAST_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	ISP_OP_TYPE_E enOpType; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x1, 0xff]*/
	ISP_YCONTRAST_MANUAL_ATTR_S stManual;
	ISP_YCONTRAST_AUTO_ATTR_S stAuto;
} ISP_YCONTRAST_ATTR_S;
//--------------------------------------------------------------------------------
// YCONTRAST >>>>>>>>
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// MONO <<<<<<<<
//--------------------------------------------------------------------------------
typedef struct _ISP_MONO_ATTR_S {
	CVI_BOOL Enable; /*RW; Range: [0x0, 0x1]*/
	CVI_U8 UpdateInterval; /*RW; Range: [0x1, 0xff]*/
} ISP_MONO_ATTR_S;
//--------------------------------------------------------------------------------
// MONO >>>>>>>>
//--------------------------------------------------------------------------------

