## 第一部分： 基础信息
name: cvi_test                                       # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: develop                                     # <必选项> 组件版本号
description: cvi测试组件                             # <必选项> 建议至少20字以上
type: common                                         # <必选项> 组件类型，为：solution, chip, board, common, sdk
tag: 第三方驱动                                      # <可选项> 组件分类，缺省值： ''
keywords:                                            # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - base
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本
# sdk_chip:                                # <可选项> 该组件依赖sdk组件，合理的依赖才能保证组件能编译、使用
#   - sdk_chip_csky_dummy: v7.4.0
#   - sdk_chip_riscv_dummy: v7.4.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.4.0
#   - aos: v7.4.0

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  include:
  internal_include:
    - test/tpu
    - test/vi
    - test/gdc
    - test/security
    - test/cviai
  libs:
  libpath:

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - test/tpu/*.c ? <CONFIG_SUPPORT_TEST_AI>
  - test/tpu_sdk/*.cpp ? <CONFIG_SUPPORT_TEST_AI>
  - test/vi/*.c ? <CONFIG_APP_TEST>
  - test/ive/*.c ? <CONFIG_SUPPORT_TEST_IVE>
  - test/vpss/*.c ? <CONFIG_APP_TEST>
  - test/venc/*.c ? <CONFIG_APP_TEST>
  - test/vdec/*.c ? <CONFIG_APP_TEST>
  - test/gdc/*.c ? <CONFIG_APP_TEST>
  - test/vo/*.c ? <CONFIG_APP_TEST>
  - test/rgn/*.c ? <CONFIG_APP_TEST>
  - test/dma/*.c ? <CONFIG_APP_TEST>
  - test/spi/*.c ? <CONFIG_APP_TEST>
  - test/sys/*.c ? <CONFIG_APP_TEST>
  - test/audio/*.c ? <CONFIG_APP_TEST>
  - test/flash/*.c ? <CONFIG_APP_TEST>
  - test/partition/*.c ? <CONFIG_APP_TEST>
  - test/security/*.c ? <CONFIG_APP_TEST>
  - test/efuse/*.c ? <CONFIG_APP_TEST>
  - test/media_venc/*.c ? <CONFIG_APP_TEST>
  - test/pwm/*.c ? <CONFIG_APP_TEST>
  - test/timer/*.c ? <CONFIG_APP_TEST>
  - test/wdt/*.c ? <CONFIG_APP_TEST>
  - test/rtc/*.c ? <CONFIG_APP_TEST>
  - test/cviai/*.c ? <CONFIG_SUPPORT_TEST_AI>
  - test/cviai/object_detection.c ? <CONFIG_SUPPORT_OBJECT_DETECTION>
  - test/cviai/aud_detect.c ? <CONFIG_SUPPORT_AUD_DETECTION>
  - test/rng/*.c ? <CONFIG_APP_TEST>
  - test/adc/*.c ? <CONFIG_APP_TEST>
  - test/disk_sd/*.c ? <CONFIG_SUPPORT_TEST_DISK>
  - test/gpio/*.c ? <CONFIG_APP_TEST>
  - test/i2c_tool/*.c ? <CONFIG_APP_TEST>
  - test/pinmux/*.c ? <CONFIG_APP_TEST>
  - test/ae/*.c ? <CONFIG_APP_TEST>
  - test/uart/*.c ? <CONFIG_APP_TEST>
  - test/gpio_pin/*.c ? <CONFIG_APP_TEST>
  - test/audio/g711/*.c ? <CONFIG_SUPPORT_TEST_G711>
  - test/audio/aac/*.c ? <CONFIG_SUPPORT_TEST_AAC>
  - test/audio/pdm/*.c ? <CONFIG_SUPPORT_TEST_PDM>
  - test/tydb_adb/*.c ? <CONFIG_SUPPORT_TEST_TYDB_ADB>
  - test/ramfs/*.c ? <CONFIG_SUPPORT_TEST_RAMFS>
  - test/tempsen/*.c ? <CONFIG_SUPPORT_TEMPSEN_TEST>
  - test/usb/usbd_cdc_acm_test.c ? <CONFIG_USBD_CDC_UART>
# - ./hichannel_test/
## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y
def_config:
  CONFIG_APP_TEST: 0
  CONFIG_SUPPORT_TEST_DISK: 0
  CONFIG_SUPPORT_OBJECT_DETECTION: 0
  CONFIG_SUPPORT_AUD_DETECTION: 0
  CONFIG_SUPPORT_TEST_AI: 0
  CONFIG_SUPPORT_TEST_G711: 0
  CONFIG_SUPPORT_TEST_AAC: 0
  CONFIG_SUPPORT_TEST_PDM: 0
  CONFIG_SUPPORT_TEST_TYDB_ADB: 0
  CONFIG_SUPPORT_TEST_RAMFS: 0
## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相对路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
install:
  - dest: "include/devices"
    source:

## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相对路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
