#!/usr/bin/env python

sensor_def = "CONFIG_SENSOR_"

chip_def = "CONFIG_CHIP_"

defconfig = [
    "CONFIG_ARCH",
    "CONFIG_CHIP",
    "CONFIG_CHIP_BIG_ARM",
    "CONFIG_CHIP_ARCH_cv180x",
    "CONFIG_CHIP_ARCH_cv181x",
    "CONFIG_RTOS_INIT_MEDIA",
    "CONFIG_COMPRESS_RTOS_BIN",
    "CONFIG_VCODEC_FIRMWARE_H",
    "CONFIG_RTOS_PARSE_PARAM",
    "CONFIG_RTOS_ANNON_MSG",
    "CONFIG_DW_UART",
    "CONFIG_VIRTUAL_UART",
    "CONFIG_C906L_DMA_ENABLE",
    "CONFIG_AUD_DRV_SEL",
    "CONFIG_H264_FW",
    "CONFIG_H265_FW",
    "CONFIG_CV180ZB_SC2003_SC2003_1l_SWITCH",
    "CONFIG_CV180ZB_SC2331_SC2331_1l_SWITCH",
    "CONFIG_CV180ZB_GC2053",
    "CONFIG_CV1811C_CV2003_1l_TRIPLE",
    "CONFIG_CV1811C_JD9165",
]
