name: mainframe
version: V7.2.2
description: mainframe
tag: 核心模块
keywords:                                      # 多标签
  - base
license: Apache license v2.0                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD

hidden: true

type: common
yoc_version:
  - v7.2
  - v7.3

depends:                                       # 该组件依赖其他的组件

build_config:
  include:
    - ./

source_file:
  - ./*.c

install:
  - dest: include/mainframe
    source:
      - "./*.h"
