mtb_version: 4
chip: cv181xc_evb

diff:
  fota_version: 0
  ram_buf: 50           #DEC     KB   ( max ram need)
  flash_buf: 16         #DEC     KB   ( buffer size)
  flash_sector: 4096    #DEC     byte ( flash sector)
  diff_mode: 010        #BIN
  double_control: 1
flash:
  base_address: 0         # 存储基地址，比如FLASH的基地址
  run_base_address: 0x80200000 # base address of Storage
  sector: 4096            # Bytes
  size: 16777216          #512kb $(sector count) * sector

partitions:
  - { name: boot0,  address: 0x000000, size: 0x00C000, filename: fip_fsbl.bin}                                 # 48 KB
  - { name: boot,   address: 0x00C000, size: 0x020000, filename: boot, load_addr: 0x80006E00 }          # 128KB
  - { name: imtb,   address: 0x02C000, size: 0x002000, filename: imtb}                                 # 8 KB
  - { name: prim,   address: 0x02E000, size: 0x480000, filename: yoc.bin, load_addr: 0x80040000, update: FULL, car: xz }          # 4.5 MB
  - { name: weight, address: 0x4AE000, size: 0x850000 }                                 # 8.3125 MB
  - { name: misc,   address: 0xCFE000, size: 0x2B0000 }                                 # 2.6875 MB
  - { name: kv,     address: 0xFAE000, size: 0x010000  }                                # 64 KB
  # - { name: spiffs, address: 0xCD0000, size: 0x100000, filename: lfs.bin }            # 1 MB
  - { name: cxrot,  address: 0xFBE000, size: 0x001000  }                                # 4 KB
  - { name: cxuser, address: 0xFBF000, size: 0x004000  }                                # 16 KB
  - { name: cxface, address: 0xFC3000, size: 0x03C000  }                                # 240 KB
