## Base Info
name: cvi_util
version: v1.0.0
description: common utilities
type: common
tag: application
keywords:
  - base
license: Apache license v2.0

## Depend Info
depends:
  # - gpio_util ? <CONFIG_UTIL_GPIO>

## Compile & Link Info
build_config:
  include:
    - include
    - gpio_util/
    - ota_util/
    - capture_image_util/
  internal_include:
  libs:
  libpath:
source_file:
  - gpio_util/*.c ? <CONFIG_UTIL_GPIO>
  - ota_util/*.c ? <CONFIG_UTIL_OTA>
  - capture_image_util/*.c ? <CONFIG_UTIL_CAPTURE_IMAGE>

## Config Info
def_config:
  CONFIG_UTIL_GPIO: 1
  CONFIG_UTIL_OTA: 1
  CONFIG_UTIL_CAPTURE_IMAGE: 0

## Install Info
install:
  - dest: "include/"
    source:
