## 第一部分： 基础信息
name: cvi_sensor                                   # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: develop                                    # <必选项> 组件版本号
description: Cvitek sensor driver SDK library.      # <必选项> 建议至少20字以上
type: common                                          # <必选项> 组件类型，为：solution, chip, board, common, sdk
#tag: 核心模块                                       # <可选项> 组件分类，缺省值： ''
keywords:                                           # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - base
license: Copyright (C) Cvitek Co., Ltd. 2019-2020. All rights reserved. # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本
# sdk_chip:                                # <可选项> 该组件依赖sdk组件，合理的依赖才能保证组件能编译、使用
#   - sdk_chip_csky_dummy: v7.4.0
#   - sdk_chip_riscv_dummy: v7.4.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.4.0
#   - aos: v7.4.0

## 第三部分：板级信息
# hw_info:                                 # 对 solution、board、chip 三个字段的改进，统称为 hw_info 字段
#   cpu_id: cpu0
#   cpu_name: CK804EF
#   vendor_name: t-head
#   chip_name: chip_light                  # <可选项> 指定芯片组件名,未设置时，使用depends中 chip 第一个组件
#   board_name: pangu_cpu0_evb             # <可选项> 指定开发板组件名，未设置时，使用depends中 board 第一个组件
#   ld_script: configs/gcc_eflash.ld       # <可选项> 连接时使用 LD 脚本，当选把未设置时，使用对应的 board 的 LD 脚本
#   flash_program: bin/flash_program.elf   # <可选项> 芯片全局烧写程序
#   toolchain_prefix: csky-abiv2-elf       # <可选项> 编译器前缀
#   cpu0:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀
#   cpu1:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <可选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀

## chip component (单处理器)
# hw_info:
#   cpu_name: CK804EF
#   ld_script: configs/gcc_eflash.ld
#   toolchain_prefix: csky-abiv2-elf
#   flash_program: bin/flash_program.elf

## chip component(多处理器)
# hw_info:
#   cpu0:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀
#   cpu:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀
#hw_info:
#  arch_name: arm
#  cpu_name: cortex-a53
#  vendor_name: cvitek
#  ld_script: gcc_csky.ld
#  toolchain_prefix: aarch64-none-elf
# flash_program: d1_flash.elf

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  include:
    - sensor_i2c
    - gcore_gc02m1
    - gcore_gc02m1_slave
    - gcore_gc02m1_multi
    - gcore_gc1054
    - gcore_gc1084
    - gcore_gc2053
    - gcore_gc2053_1L
    - gcore_gc2093
    - gcore_gc2083_1L
    - gcore_gc4653
    - opnous_opn8018
    - sms_sc200ai
    - sms_sc2336
    - sms_sc2336_1L
    - sms_sc2336p
    - sms_sc2336p_1L
    - sms_sc3336
    - sms_sc030iot
    - sms_sc201cs
    - sms_sc201cs_slave
    - sms_sc201cs_multi
    - sms_sc031iot
    - sms_sc031iot_raw
    - sony_imx307
    - sony_imx327
    - byd_bf314a
    - byd_bf2253l
    - sms_sc1336_2L
    - ov_ov5647
    - sms_sc202cs
    - sms_sc202cs_slave
    - sms_sc202cs_multi
    - sms_sc301iot
    - byd_bf2257cs
    - byd_bf2257cs_slave
    - spix_sp2509
    - sms_sc530ai_4L
    - sms_sc230ai
    - sms_sc230ai_slave
    - ov_ov02b10
    - cista_c2599
# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
## middleware
  - sensor_i2c/*.c
  - gcore_gc02m1/*.c ? <CONFIG_SENSOR_GCORE_GC02M1>
  - gcore_gc02m1_slave/*.c ? <CONFIG_SENSOR_GCORE_GC02M1_SLAVE>
  - gcore_gc02m1_multi/*.c ? <CONFIG_SENSOR_GCORE_GC02M1_MULTI>
  - gcore_gc1054/*.c ? <CONFIG_SENSOR_GCORE_GC1054>
  - gcore_gc1084/*.c ? <CONFIG_SENSOR_GCORE_GC1084>
  - gcore_gc2053/*.c ? <CONFIG_SENSOR_GCORE_GC2053>
  - gcore_gc2053_1L/*.c ? <CONFIG_SENSOR_GCORE_GC2053_1L>
  - gcore_gc2093/*.c ? <CONFIG_SENSOR_GCORE_GC2093>
  - gcore_gc2083_1L/*.c ? <CONFIG_SENSOR_GCORE_GC2083_1L>
  - gcore_gc4653/*.c ? <CONFIG_SENSOR_GCORE_GC4653>
  - opnous_opn8018/*.c ? <CONFIG_SENSOR_OPNOUS_OPN8018>
  - sms_sc200ai/*.c ? <CONFIG_SENSOR_SMS_SC200AI>
  - sms_sc2336/*.c ? <CONFIG_SENSOR_SMS_SC2336>
  - sms_sc2336_1L/*.c ? <CONFIG_SENSOR_SMS_SC2336_1L>
  - sms_sc2336p/*.c ? <CONFIG_SENSOR_SMS_SC2336P>
  - sms_sc2336p_1L/*.c ? <CONFIG_SENSOR_SMS_SC2336P_1L>
  - sms_sc3336/*.c ? <CONFIG_SENSOR_SMS_SC3336>
  - sms_sc030iot/*.c ? <CONFIG_SENSOR_SMS_SC030IOT>
  - sms_sc201cs/*.c ? <CONFIG_SENSOR_SMS_SC201CS>
  - sms_sc201cs_slave/*.c ? <CONFIG_SENSOR_SMS_SC201CS_SLAVE>
  - sms_sc201cs_multi/*.c ? <CONFIG_SENSOR_SMS_SC201CS_MULTI>
  - sms_sc031iot/*.c ? <CONFIG_SENSOR_SMS_SC031IOT>
  - sms_sc031iot_raw/*.c ? <CONFIG_SENSOR_SMS_SC031IOT_RAW>
  - sony_imx307/*.c ? <CONFIG_SENSOR_SONY_IMX307>
  - sony_imx327/*.c ? <CONFIG_SENSOR_SONY_IMX327>
  - byd_bf314a/*.c ? <CONFIG_SENSOR_BYD_BF314A>
  - byd_bf2253l/*.c ? <CONFIG_SENSOR_BYD_BF2253L>
  - sms_sc1336_2L/*.c ? <CONFIG_SENSOR_SMS_SC1336_2L>
  - ov_ov5647/*.c ? <CONFIG_SENSOR_OV_OV5647>
  - sms_sc202cs/*.c ? <CONFIG_SENSOR_SMS_SC202CS>
  - sms_sc202cs_slave/*.c ? <CONFIG_SENSOR_SMS_SC202CS_SLAVE>
  - sms_sc202cs_multi/*.c ? <CONFIG_SENSOR_SMS_SC202CS_MULTI>
  - sms_sc230ai/*.c ? <CONFIG_SENSOR_SMS_SC230AI>
  - sms_sc230ai_slave/*.c ? <CONFIG_SENSOR_SMS_SC230AI_SLAVE>
  - sms_sc301iot/*.c ? <CONFIG_SENSOR_SMS_SC301IOT>
  - sms_sc530ai_4L/*.c ? <CONFIG_SENSOR_SMS_SC530AI_4L>
  - byd_bf2257cs/*.c ? <CONFIG_SENSOR_BYD_BF2257CS>
  - byd_bf2257cs_slave/*.c ? <CONFIG_SENSOR_BYD_BF2257CS_SLAVE>
  - spix_sp2509/*.c ? <CONFIG_SENSOR_SPIX_SP2509>
  - ov_ov02b10/*.c ? <CONFIG_SENSOR_OV_OV02B10>
  - cista_c2599/*.c ? <CONFIG_SENSOR_CISTA_C2599>
## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y
def_config:

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相对路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
#install:
install:
  - dest: "include/"
    source:

## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相对路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
