
## 第一部分： 基础信息
name: lvgl_9_1_0                                          # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: develop                                     # <必选项> 组件版本号
description: LVGL 组件是一个免费的开源图形库，提供了创建嵌入式GUI所需的一切，具有易于使用的组件，美观的视觉效果和低内存占用等特点。 # <必选项> 建议至少20字以上
type: common                                        # <必选项> 组件类型，为：solution, chip, board, common, sdk
tag: 核心模块                                       # <可选项> 组件分类，缺省值： ''
keywords:                                           # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - base
license: MIT license                                # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# sdk_chip:                                # <可选项> 该组件依赖sdk组件，合理的依赖才能保证组件能编译、使用
#   - sdk_chip_csky_dummy: v7.4.3
#   - sdk_chip_riscv_dummy: v7.4.3
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  cflag: '-Wno-nonnull-compare -O3'
  include:
    - .
    - src
    - src/core
    - src/display
    - src/draw
    - src/drivers
    - src/font
    - src/indev
    - src/layouts
    - src/libs
    - src/misc
    - src/osal
    - src/others
    - src/stdlib
    - src/themes
    - src/tick
    - src/widgets
    - demos
    - examples
    - porting

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - "src/*.c"
  - "src/core/*.c"
  - "src/display/*.c"
  - "src/draw/*.c"
  - "src/draw/sw/*.c"
  - "src/draw/sw/blend/*.c"
  - "src/font/*.c"
  - "src/indev/*.c"
  - "src/layouts/*.c"
  - "src/layouts/flex/*.c"
  - "src/layouts/grid/*.c"
  - "src/libs/barcode/*.c"
  - "src/libs/bin_decoder/*.c"
  - "src/libs/bmp/*.c"
  - "src/libs/ffmpeg/*.c"
  - "src/libs/freetype/*.c"
  - "src/libs/fsdrv/*.c"
  - "src/libs/gif/*.c"
  - "src/libs/libjpeg_turbo/*.c"
  - "src/libs/libpng/*.c"
  - "src/libs/lodepng/*.c"
  - "src/libs/lz4/*.c"
  - "src/libs/qrcode/*.c"
  - "src/libs/rle/*.c"
  - "src/libs/rlottie/*.c"
  - "src/libs/thorvg/*.c"
  - "src/libs/tiny_ttf/*.c"
  - "src/libs/tjpgd/*.c"
  - "src/misc/*.c"
  - "src/misc/cache/*.c"
  - "src/osal/*.c"
  - "src/others/file_explorer/*.c"
  - "src/others/fragment/*.c"
  - "src/others/gridnav/*.c"
  - "src/others/ime/*.c"
  - "src/others/imgfont/*.c"
  - "src/others/monkey/*.c"
  - "src/others/observer/*.c"
  - "src/others/snapshot/*.c"
  - "src/others/sysmon/*.c"
  - "src/others/vg_lite_tvg/*.c"
  - "src/stdlib/*.c"
  - "src/stdlib/builtin/*.c"
  - "src/stdlib/clib/*.c"
  - "src/stdlib/micropython/*.c"
  - "src/stdlib/rtthread/*.c"
  - "src/themes/*.c"
  - "src/themes/default/*.c"
  - "src/themes/mono/*.c"
  - "src/themes/simple/*.c"
  - "src/tick/*.c"
  - "src/widgets/animimage/*.c"
  - "src/widgets/arc/*.c"
  - "src/widgets/bar/*.c"
  - "src/widgets/button/*.c"
  - "src/widgets/buttonmatrix/*.c"
  - "src/widgets/calendar/*.c"
  - "src/widgets/canvas/*.c"
  - "src/widgets/chart/*.c"
  - "src/widgets/checkbox/*.c"
  - "src/widgets/dropdown/*.c"
  - "src/widgets/image/*.c"
  - "src/widgets/imagebutton/*.c"
  - "src/widgets/keyboard/*.c"
  - "src/widgets/label/*.c"
  - "src/widgets/led/*.c"
  - "src/widgets/line/*.c"
  - "src/widgets/list/*.c"
  - "src/widgets/menu/*.c"
  - "src/widgets/msgbox/*.c"
  - "src/widgets/objx_templ/*.c"
  - "src/widgets/roller/*.c"
  - "src/widgets/scale/*.c"
  - "src/widgets/slider/*.c"
  - "src/widgets/span/*.c"
  - "src/widgets/spinbox/*.c"
  - "src/widgets/spinner/*.c"
  - "src/widgets/switch/*.c"
  - "src/widgets/table/*.c"
  - "src/widgets/tabview/*.c"
  - "src/widgets/textarea/*.c"
  - "src/widgets/tileview/*.c"
  - "src/widgets/win/*.c"

  # - "porting/*.c"

  - "demos/benchmark/*.c"
  - "demos/benchmark/assets/*.c"
  - "demos/flex_layout/*.c"
  - "demos/keypad_encoder/*.c"
  - "demos/multilang/*.c"
  - "demos/multilang/assets/*.c"
  - "demos/music/*.c"
  - "demos/music/assets/*.c"
  - "demos/render/*.c"
  - "demos/render/assets/*.c"
  - "demos/scroll/*.c"
  - "demos/stress/*.c"
  - "demos/transform/*.c"
  - "demos/transform/assets/*.c"
  - "demos/vector_graphic/*.c"
  - "demos/vector_graphic/assets/*.c"
  - "demos/widgets/*.c"
  - "demos/widgets/assets/*.c"




## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y
def_config:                              # 组件的可配置项
  LV_CONF_INCLUDE_SIMPLE: 1
  LV_LVGL_H_INCLUDE_SIMPLE: 1

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相对路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
# install:
#  - dest: "include/lvgl/src"
#    source:
#      - "src/*.h"
#  - dest: "include/lvgl/src/lv_core"
#    source:
#      - "src/lv_core/*.h"
#  - dest: "include/lvgl/src/lv_draw"
#    source:
#      - "src/lv_draw/*.h"
#  - dest: "include/lvgl/src/lv_font"
#    source:
#      - "src/lv_font/*.h"
#  - dest: "include/lvgl/src/lv_hal"
#    source:
#      - "src/lv_hal/*.h"
#  - dest: "include/lvgl/src/lv_misc"
#    source:
#      - "src/lv_misc/*.h"
#  - dest: "include/lvgl/src/lv_objx"
#    source:
#      - "src/lv_objx/*.h"
#  - dest: "include/lvgl/src/lv_themes"
#    source:
#      - "src/lv_themes/*.h"

## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相当路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
