mtb_version: 4
chip: cv181xc_evb

diff:
  fota_version: 0
  ram_buf: 50           #DEC     KB   ( max ram need)
  flash_buf: 16         #DEC     KB   ( buffer size)
  flash_sector: 4096    #DEC     byte ( flash sector)
  diff_mode: 010        #BIN
  double_control: 1

storages:
  - name: spinor            # eflash/spinor/spinand/emmc_boot1/emmc_boot2/emmc_user/emmc_rpmb/sd/usb
    base_address: 0         # 存储基地址，比如FLASH的基地址
    run_base_address: 0x80000000 # base address of Storage
    sector: 4096            # Bytes
    size: 16777216          # Total Bytes
  - name: usb               # eflash/spinor/spinand/emmc_boot1/emmc_boot2/emmc_user/emmc_rpmb/sd/usb
    base_address: 0         # 存储基地址，比如FLASH的基地址
    run_base_address: 0x8000C000 # base address of Storage
    block: 512              # Bytes
    size: 0                 # Total Bytes
    hot_plug: true
  - name: sd                # eflash/spinor/spinand/emmc_boot1/emmc_boot2/emmc_user/emmc_rpmb/sd/usb
    base_address: 0         # 存储基地址，比如FLASH的基地址
    run_base_address: 0x8000C000 # base address of Storage
    block: 512              # Bytes
    size: 0                 # Total Bytes
    hot_plug: true

partitions:
  - { name: boot0,  address: 0x000000, size: 0x00C000, index: 0, file: boot0}                                 # 48 KB
  - { name: boot,   address: 0x00C000, size: 0x020000, index: 0, file: boot}          # 128KB
  - { name: imtb,   address: 0x02C000, size: 0x002000, index: 0, file: imtb}                                  # 8 KB
  - { name: envab,  address: 0x02E000, size: 0x004000, index: 0} # for ab switch, size must be 2*sector+1024B at least
  - { name: prima,  address: 0x032000, size: 0x6B0000, index: 0, file: prim, load_addr: 0x80040000, verify: true, update: AB }
  - { name: primb,  address: 0x6E2000, size: 0x1B0000, index: 0, load_addr: 0x80040000, verify: true }
  - { name: lfs,    address: 0x892000, size: 0x480000, index: 0 }                                 # 4.5 MB
  - { name: kv,     address: 0xD12000, size: 0x010000, index: 0  }                                # 64 KB
  - { name: afrot,  address: 0xD22000, size: 0x001000, index: 0  }                                # 4 KB
  - { name: kp,     address: 0xD23000, size: 0x001000, index: 0  }                                # 4 KB
  - { name: fatfs,  address: 0x000000, size: 0, index: 2 }                                        # size = 0 let device decide size